### ISSUE TITLE
API request yields 404 response

### ISSUE THREAD

**Issue by ewinge** [echr-od/ECHR-OD_explorer#11]
I have tried some of the URLs listed in the API documentation at https://echr-opendata.eu/api/v1/docs#/ .
They all yield "404 page not found" responses.

Some examples of URLs which don't currently work:
https://echr-opendata.eu/cases?page=1&limit=10
https://echr-opendata.eu/stats
https://echr-opendata.eu/version

**Comment by aquemy** [comment]
@ewinge thank you for opening this issue. I moved it here as it concerns the Explorer (the frontend application).

The problem is now solved and the frontend application in production has been updated and restarted. It should work now!
